import Navbar from "@/components/Navbar"
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // pilih weight yang kamu butuhkan
})

export const metadata = {
  title: "Samarinda Hash House Harriers",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.variable}  h-full antialiased`}
    >
      <Navbar />
      <body className="min-h-full flex flex-col bg-[#FCF4E6]">{children}</body>
    </html>
  );
}
