import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: '--font-poppins',
})

export const metadata = {
  title: "Samarinda Hash House Harriers",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.variable}  h-full antialiased`}
    >

      <body className="min-h-full flex flex-col bg-bg-colors text-text-colors">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
