import Navbar from "@/src/components/Navbar";
import Footer from "@/src/components/Footer";
import "./globals.css";
import { Crimson_Pro } from 'next/font/google'

const crimsonpro = Crimson_Pro({
  subsets: ['latin'],
})
export const metadata = {
  title: "Samarinda Hash House Harriers",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={` h-full antialiased ${crimsonpro.className}`}
    >
      

      <body className="min-h-full flex flex-col bg-bg-colors text-text-colors">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
