import Navbar from "@/src/components/Navbar";
import Footer from "@/src/components/Footer";
import "./globals.css";
import { Libre_Baskerville, Young_Serif } from 'next/font/google';

const libreB = Libre_Baskerville({
  subsets: ['latin'],
})
const youngS = Young_Serif({
  weight: '400',
  subsets: ['latin'],
  variable: "--font-young"
})

export const metadata = {
  title: "Samarinda Hash House Harriers",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={` h-full antialiased ${libreB.className} ${youngS.variable}`}
    >

      <body className="min-h-full flex flex-col bg-primary-light-active text-neutral-text">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
